- id: doi:10.3390/proteomes9020027
  title: Phosphorylation-Dependent Interactome of Ryanodine Receptor Type 2 in the
    Heart
  authors:
  - David Y. Chiang
  - Satadru Lahiri
  - Guoliang Wang
  - Jason Karch
  - Meng C. Wang
  - Sung Y. Jung
  - Albert J. R. Heck
  - Arjen Scholten
  - Xander H. T. Wehrens
  publisher: Proteomes
  date: '2021-06-07'
  link: https://doi.org/gkg6q7
  orcid: 0000-0002-5883-6383
  plugin: orcid.py
  file: orcid.yaml

- id: doi:10.1038/s44161-023-00294-y
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs44161-023-00294-y/MediaObjects/44161_2023_294_Fig1_HTML.png?as=webp

- id: doi:10.1016/j.jacep.2022.08.022
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2405500X22007332-fx1.jpg

- id: doi:10.1161/CIRCRESAHA.120.318643
  image: https://www.ahajournals.org/cms/10.1161/CIRCRESAHA.120.318643/asset/5c339344-9f9e-4e75-abc2-503dbfd781a4/assets/graphic/circresaha.120.318643.fig08.jpg

- id: doi:10.1161/CIRCEP.115.003098
  image: https://www.ahajournals.org/cms/10.1161/CIRCEP.115.003098/asset/938396a2-2126-4e94-9c46-a25c699e5451/assets/graphic/1105fig01.jpeg

- id: PMID:36435694

- id: doi:10.1074/jbc.RA120.015216

- id: PMCID:PMC8453299

- id: PMCID:PMC11041666

- id: https://doi.org/10.1016/j.hrthm.2025.03.029

- id: PMCID:PMC9376964

- id: doi:10.1161/CIRCRESAHA.123.323231
  image: https://www.ahajournals.org/cms/10.1161/CIRCRESAHA.123.323231/asset/92113e94-03e0-41ee-a71f-6cc09cd7e7ca/assets/graphic/circresaha.123.323231.fig09.jpg

- id: PMCID:PMC8298292 

- id: PMID:35210625
  image: https://cdn.ncbi.nlm.nih.gov/pmc/blobs/33af/9376964/83875dad415e/nihms-1817393-f0007.jpg