- id: doi:10.3390/proteomes9020027
  title: Phosphorylation-Dependent Interactome of Ryanodine Receptor Type 2 in the
    Heart
  authors:
  - David Y. Chiang
  - Satadru Lahiri
  - Guoliang Wang
  - Jason Karch
  - Meng C. Wang
  - Sung Y. Jung
  - Albert J. R. Heck
  - Arjen Scholten
  - Xander H. T. Wehrens
  publisher: Proteomes
  date: '2021-06-07'
  link: https://doi.org/gkg6q7
  orcid: 0000-0002-5883-6383
  plugin: orcid.py
  file: orcid.yaml

